const VeyralI18n=(()=>{
  const english={
    'Выберите локацию':'Choose a location','Настройки':'Settings','Обновить список':'Refresh list','Профиль WireGuard не добавлен':'No WireGuard profile','Импортируйте файл .conf в настройках.':'Import a .conf file in Settings.',
    'ПОДКЛЮЧЕНИЕ ВЫКЛЮЧЕНО':'NOT CONNECTED','СЕРВЕР ВЫБРАН · НЕ ПОДКЛЮЧЕНО':'SERVER SELECTED · NOT CONNECTED','ТУННЕЛЬ ВКЛЮЧЁН':'TUNNEL ACTIVE',
    'Проверяем серверы в фоне':'Checking servers in the background','Нажмите на страну в списке':'Select a location from the list','Город не определён':'City unknown','город не определён':'city unknown',
    'ОТКЛИК':'LATENCY','Google: где я ↗':'Google: where am I ↗','Выберите':'Select','Пуск':'Connect','Стоп':'Disconnect','Подождите…':'Please wait…',
    'Локации':'Locations','Поиск...':'Searching...','Страна или город':'Country or city','Поиск по стране или городу':'Search by country or city',
    'Тип прокси':'Proxy type','Все типы':'All types','СТРАНА И ГОРОД':'COUNTRY AND CITY','ПИНГ':'PING','Карта сети':'Network map','0 стран':'0 countries',
    'Точки появятся после проверки':'Locations appear after scanning','Быстрый':'Fast','Средний':'Medium','Высокий пинг':'High latency','Загружаем список':'Loading list',
    'Выбранная локация':'Selected location','Список локаций':'Location list','Карта доступных прокси':'Available proxy map','Глобус с доступными прокси':'Globe with available proxies',
    'Свернуть':'Minimize','Развернуть':'Maximize','Закрыть':'Close','Язык':'Language','Маршрутизация':'Routing',
    'Весь компьютер':'Entire computer','Только выбранные программы':'Selected apps only','Все, кроме выбранных программ':'All except selected apps',
    'Добавить программу .exe':'Add .exe program','DNS запросы системы проходят через туннель. После изменения маршрута переподключитесь.':'System DNS requests use the tunnel. Reconnect after changing routing.',
    'Свой WireGuard':'Your WireGuard','Профиль не импортирован':'No profile imported','Импорт .conf':'Import .conf','Удалить':'Remove',
    'Приватный ключ хранится в защищённом хранилище Windows. Для подключения нужен свой WireGuard сервер.':'The private key is stored in Windows secure storage. You need your own WireGuard server.',
    'Свой сервер':'Your server','Мой WireGuard':'My WireGuard','Неизвестная страна':'Unknown country','Качество пинга':'Ping quality','из':'of',
    'Маршрут включён · проверьте IP в программе':'Routing is active · check the IP in your app','Выходной IP ПК':'PC exit IP','проверить ↗':'check ↗',
    'Ничего не найдено':'No results','Ищем доступные локации':'Finding available locations','Нет доступных серверов':'No available servers','Подготовка':'Getting ready',
    'Серверы появятся здесь по мере проверки.':'Servers will appear as they are checked.','Попробуйте другой город, страну или тип.':'Try another city, country, or type.',
    'Обновите список позже.':'Refresh the list later.','Загружаем публичные списки.':'Loading proxy lists.',
    'Обновление списка':'Refreshing list','Загрузка списка':'Loading list','Ошибка загрузки':'Failed to load list','Не удалось загрузить список':'Failed to load list',
    'Сначала остановите текущее подключение':'Disconnect the current server first','Не удалось отключить прокси':'Could not disconnect','Прокси отключён':'Disconnected',
    'Ошибка подключения':'Connection failed','Не удалось включить туннель':'Could not start the tunnel','Подключено':'Connected','Маршрут выбранных программ включён':'Selected app routing is active',
    'Туннель включён; выходной IP проверен':'Tunnel active; exit IP verified','Маршрут включён. Проверьте IP в выбранной программе':'Routing active. Check the IP in the selected app.',
    'Не удалось изменить настройки Windows':'Could not change Windows settings','Прокси отключён: сервер перестал отвечать':'Disconnected: server stopped responding',
    'Пройдите CAPTCHA в открытом окне Google':'Complete CAPTCHA in the Google window','Удалить программу':'Remove program','Профиль WireGuard импортирован':'WireGuard profile imported',
    'Поиск серверов':'Finding servers','Рукопожатие':'Handshake','Маршрутизация':'Routing','Проверка IP':'Checking IP','Запуск WireGuard':'Starting WireGuard','Проверка серверов':'Checking servers',
    'Сначала остановите соединение':'Disconnect first','Системный прокси пока доступен только в Windows':'System proxy is available only on Windows',
    'Соединение уже включено':'Already connected','Выберите программу в настройках маршрутизации':'Select a program in Routing settings',
    'Обновите список и выберите сервер':'Refresh the list and select a server','Серверы этой страны не ответили за 4 секунды. Выберите другую локацию':'Servers in this country did not respond within four seconds. Choose another location.',
    'Подождите завершения подключения':'Wait for the connection attempt to finish','Туннель доступен только в Windows':'The tunnel is available only on Windows',
    'Сначала импортируйте файл WireGuard .conf':'Import a WireGuard .conf file first','Сначала подключитесь к серверу':'Connect to a server first',
    'В режиме выбранных программ проверяйте IP внутри этих программ':'In selected-app mode, check the IP inside those apps','Координаты выхода неизвестны':'Exit coordinates are unknown'
  };
  const translations={
    tr:{
      'Выберите локацию':'Konum seçin','Настройки':'Ayarlar','Обновить список':'Listeyi yenile','Профиль WireGuard не добавлен':'WireGuard profili yok','Импортируйте файл .conf в настройках.':'Ayarlardan bir .conf dosyası içe aktarın.','ПОДКЛЮЧЕНИЕ ВЫКЛЮЧЕНО':'BAĞLI DEĞİL','СЕРВЕР ВЫБРАН · НЕ ПОДКЛЮЧЕНО':'SUNUCU SEÇİLDİ · BAĞLI DEĞİL','ТУННЕЛЬ ВКЛЮЧЁН':'TÜNEL ETKİN',
      'Проверяем серверы в фоне':'Sunucular arka planda kontrol ediliyor','Нажмите на страну в списке':'Listeden bir konum seçin','Город не определён':'Şehir bilinmiyor','город не определён':'şehir bilinmiyor','ОТКЛИК':'GECİKME','Google: где я ↗':'Google: neredeyim ↗',
      'Выберите':'Seçin','Пуск':'Bağlan','Стоп':'Bağlantıyı kes','Подождите…':'Lütfen bekleyin…','Локации':'Konumlar','Страна или город':'Ülke veya şehir','Поиск по стране или городу':'Ülke veya şehir ara','Тип прокси':'Proxy türü','Все типы':'Tüm türler','СТРАНА И ГОРОД':'ÜLKE VE ŞEHİR','ПИНГ':'PING','Карта сети':'Ağ haritası',
      'Точки появятся после проверки':'Konumlar taramadan sonra görünecek','Быстрый':'Hızlı','Средний':'Orta','Высокий пинг':'Yüksek gecikme','Загружаем список':'Liste yükleniyor','Выбранная локация':'Seçilen konum','Список локаций':'Konum listesi','Карта доступных прокси':'Kullanılabilir proxy haritası','Глобус с доступными прокси':'Kullanılabilir proxy küresi',
      'Свернуть':'Küçült','Развернуть':'Büyüt','Закрыть':'Kapat','Язык':'Dil','Маршрутизация':'Yönlendirme','Весь компьютер':'Tüm bilgisayar','Только выбранные программы':'Yalnızca seçilen uygulamalar','Все, кроме выбранных программ':'Seçilenler hariç tüm uygulamalar','Добавить программу .exe':'.exe uygulaması ekle',
      'DNS запросы системы проходят через туннель. После изменения маршрута переподключитесь.':'Sistem DNS istekleri tünelden geçer. Yönlendirmeyi değiştirdikten sonra yeniden bağlanın.','Свой WireGuard':'Kendi WireGuard sunucunuz','Профиль не импортирован':'Profil içe aktarılmadı','Импорт .conf':'.conf içe aktar','Удалить':'Kaldır','Приватный ключ хранится в защищённом хранилище Windows. Для подключения нужен свой WireGuard сервер.':'Özel anahtar Windows güvenli deposunda saklanır. Kendi WireGuard sunucunuz gerekir.',
      'Свой сервер':'Kendi sunucunuz','Мой WireGuard':'WireGuard sunucum','Неизвестная страна':'Bilinmeyen ülke','Качество пинга':'Ping kalitesi','из':'/','Маршрут включён · проверьте IP в программе':'Yönlendirme etkin · IP adresini uygulamada kontrol edin','Выходной IP ПК':'Bilgisayar çıkış IP adresi','проверить ↗':'kontrol et ↗',
      'Ничего не найдено':'Sonuç yok','Ищем доступные локации':'Kullanılabilir konumlar aranıyor','Нет доступных серверов':'Kullanılabilir sunucu yok','Подготовка':'Hazırlanıyor','Серверы появятся здесь по мере проверки.':'Sunucular kontrol edildikçe burada görünür.','Попробуйте другой город, страну или тип.':'Başka bir şehir, ülke veya tür deneyin.','Обновите список позже.':'Listeyi daha sonra yenileyin.','Загружаем публичные списки.':'Proxy listeleri yükleniyor.',
      'Обновление списка':'Liste yenileniyor','Загрузка списка':'Liste yükleniyor','Ошибка загрузки':'Liste yüklenemedi','Не удалось загрузить список':'Liste yüklenemedi','Сначала остановите текущее подключение':'Önce mevcut bağlantıyı kesin','Не удалось отключить прокси':'Bağlantı kesilemedi','Прокси отключён':'Bağlantı kesildi','Ошибка подключения':'Bağlantı başarısız','Не удалось включить туннель':'Tünel başlatılamadı','Подключено':'Bağlandı','Маршрут выбранных программ включён':'Seçilen uygulamalar için yönlendirme etkin',
      'Туннель включён; выходной IP проверен':'Tünel etkin; çıkış IP adresi doğrulandı','Маршрут включён. Проверьте IP в выбранной программе':'Yönlendirme etkin. IP adresini seçilen uygulamada kontrol edin.','Не удалось изменить настройки Windows':'Windows ayarları değiştirilemedi','Прокси отключён: сервер перестал отвечать':'Bağlantı kesildi: sunucu yanıt vermiyor','Пройдите CAPTCHA в открытом окне Google':'Açık Google penceresinde CAPTCHA işlemini tamamlayın','Удалить программу':'Uygulamayı kaldır','Профиль WireGuard импортирован':'WireGuard profili içe aktarıldı',
      'Поиск серверов':'Sunucular aranıyor','Рукопожатие':'El sıkışma','Проверка IP':'IP kontrol ediliyor','Запуск WireGuard':'WireGuard başlatılıyor','Проверка серверов':'Sunucular kontrol ediliyor','Сначала остановите соединение':'Önce bağlantıyı kesin','Соединение уже включено':'Zaten bağlı','Выберите программу в настройках маршрутизации':'Yönlendirme ayarlarından bir uygulama seçin','Обновите список и выберите сервер':'Listeyi yenileyin ve bir sunucu seçin','Подождите завершения подключения':'Bağlantı denemesinin bitmesini bekleyin','Сначала импортируйте файл WireGuard .conf':'Önce WireGuard .conf dosyasını içe aktarın'
    },
    de:{
      'Выберите локацию':'Standort wählen','Настройки':'Einstellungen','Обновить список':'Liste aktualisieren','Профиль WireGuard не добавлен':'Kein WireGuard-Profil','Импортируйте файл .conf в настройках.':'In den Einstellungen eine .conf-Datei importieren.','ПОДКЛЮЧЕНИЕ ВЫКЛЮЧЕНО':'NICHT VERBUNDEN','СЕРВЕР ВЫБРАН · НЕ ПОДКЛЮЧЕНО':'SERVER GEWÄHLT · NICHT VERBUNDEN','ТУННЕЛЬ ВКЛЮЧЁН':'TUNNEL AKTIV',
      'Проверяем серверы в фоне':'Server werden im Hintergrund geprüft','Нажмите на страну в списке':'Standort in der Liste wählen','Город не определён':'Stadt unbekannt','город не определён':'Stadt unbekannt','ОТКЛИК':'LATENZ','Google: где я ↗':'Google: Wo bin ich? ↗','Выберите':'Wählen','Пуск':'Verbinden','Стоп':'Trennen','Подождите…':'Bitte warten…',
      'Локации':'Standorte','Страна или город':'Land oder Stadt','Поиск по стране или городу':'Land oder Stadt suchen','Тип прокси':'Proxy-Typ','Все типы':'Alle Typen','СТРАНА И ГОРОД':'LAND UND STADT','ПИНГ':'PING','Карта сети':'Netzwerkkarte','Точки появятся после проверки':'Standorte erscheinen nach der Prüfung','Быстрый':'Schnell','Средний':'Mittel','Высокий пинг':'Hohe Latenz','Загружаем список':'Liste wird geladen',
      'Выбранная локация':'Gewählter Standort','Список локаций':'Standortliste','Карта доступных прокси':'Karte verfügbarer Proxys','Глобус с доступными прокси':'Globus mit verfügbaren Proxys','Свернуть':'Minimieren','Развернуть':'Maximieren','Закрыть':'Schließen','Язык':'Sprache','Маршрутизация':'Routing','Весь компьютер':'Gesamter Computer','Только выбранные программы':'Nur ausgewählte Programme','Все, кроме выбранных программ':'Alle außer ausgewählten Programmen','Добавить программу .exe':'.exe-Programm hinzufügen',
      'DNS запросы системы проходят через туннель. После изменения маршрута переподключитесь.':'System-DNS-Anfragen laufen durch den Tunnel. Nach Routing-Änderungen erneut verbinden.','Свой WireGuard':'Eigenes WireGuard','Профиль не импортирован':'Kein Profil importiert','Импорт .conf':'.conf importieren','Удалить':'Entfernen','Приватный ключ хранится в защищённом хранилище Windows. Для подключения нужен свой WireGuard сервер.':'Der private Schlüssel wird sicher in Windows gespeichert. Ein eigener WireGuard-Server ist erforderlich.',
      'Свой сервер':'Eigener Server','Мой WireGuard':'Mein WireGuard','Неизвестная страна':'Unbekanntes Land','Качество пинга':'Ping-Qualität','из':'von','Маршрут включён · проверьте IP в программе':'Routing aktiv · IP in der Anwendung prüfen','Выходной IP ПК':'Ausgangs-IP des PCs','проверить ↗':'prüfen ↗','Ничего не найдено':'Keine Ergebnisse','Ищем доступные локации':'Verfügbare Standorte werden gesucht','Нет доступных серверов':'Keine Server verfügbar','Подготовка':'Vorbereitung',
      'Серверы появятся здесь по мере проверки.':'Server erscheinen hier während der Prüfung.','Попробуйте другой город, страну или тип.':'Anderes Land, andere Stadt oder anderen Typ versuchen.','Обновите список позже.':'Liste später aktualisieren.','Загружаем публичные списки.':'Proxy-Listen werden geladen.','Обновление списка':'Liste wird aktualisiert','Загрузка списка':'Liste wird geladen','Ошибка загрузки':'Liste konnte nicht geladen werden','Не удалось загрузить список':'Liste konnte nicht geladen werden',
      'Сначала остановите текущее подключение':'Zuerst die aktuelle Verbindung trennen','Не удалось отключить прокси':'Trennen fehlgeschlagen','Прокси отключён':'Verbindung getrennt','Ошибка подключения':'Verbindung fehlgeschlagen','Не удалось включить туннель':'Tunnel konnte nicht gestartet werden','Подключено':'Verbunden','Маршрут выбранных программ включён':'Routing für ausgewählte Programme aktiv','Туннель включён; выходной IP проверен':'Tunnel aktiv; Ausgangs-IP geprüft','Маршрут включён. Проверьте IP в выбранной программе':'Routing aktiv. IP in der gewählten Anwendung prüfen.',
      'Не удалось изменить настройки Windows':'Windows-Einstellungen konnten nicht geändert werden','Прокси отключён: сервер перестал отвечать':'Getrennt: Server antwortet nicht mehr','Пройдите CAPTCHA в открытом окне Google':'CAPTCHA im geöffneten Google-Fenster lösen','Удалить программу':'Programm entfernen','Профиль WireGuard импортирован':'WireGuard-Profil importiert','Поиск серверов':'Server werden gesucht','Рукопожатие':'Handshake','Проверка IP':'IP wird geprüft','Запуск WireGuard':'WireGuard wird gestartet','Проверка серверов':'Server werden geprüft','Сначала остановите соединение':'Zuerst Verbindung trennen','Соединение уже включено':'Bereits verbunden','Выберите программу в настройках маршрутизации':'Programm in den Routing-Einstellungen wählen','Обновите список и выберите сервер':'Liste aktualisieren und Server wählen','Подождите завершения подключения':'Warten, bis der Verbindungsversuch beendet ist','Сначала импортируйте файл WireGuard .conf':'Zuerst eine WireGuard-.conf-Datei importieren'
    },
    fr:{
      'Выберите локацию':'Choisir un emplacement','Настройки':'Paramètres','Обновить список':'Actualiser la liste','Профиль WireGuard не добавлен':'Aucun profil WireGuard','Импортируйте файл .conf в настройках.':'Importez un fichier .conf dans les paramètres.','ПОДКЛЮЧЕНИЕ ВЫКЛЮЧЕНО':'NON CONNECTÉ','СЕРВЕР ВЫБРАН · НЕ ПОДКЛЮЧЕНО':'SERVEUR CHOISI · NON CONNECTÉ','ТУННЕЛЬ ВКЛЮЧЁН':'TUNNEL ACTIF',
      'Проверяем серверы в фоне':'Vérification des serveurs en arrière-plan','Нажмите на страну в списке':'Choisissez un emplacement dans la liste','Город не определён':'Ville inconnue','город не определён':'ville inconnue','ОТКЛИК':'LATENCE','Google: где я ↗':'Google : où suis-je ? ↗','Выберите':'Choisir','Пуск':'Se connecter','Стоп':'Déconnecter','Подождите…':'Patientez…',
      'Локации':'Emplacements','Страна или город':'Pays ou ville','Поиск по стране или городу':'Rechercher un pays ou une ville','Тип прокси':'Type de proxy','Все типы':'Tous les types','СТРАНА И ГОРОД':'PAYS ET VILLE','ПИНГ':'PING','Карта сети':'Carte du réseau','Точки появятся после проверки':'Les emplacements apparaîtront après l’analyse','Быстрый':'Rapide','Средний':'Moyen','Высокий пинг':'Latence élevée','Загружаем список':'Chargement de la liste',
      'Выбранная локация':'Emplacement choisi','Список локаций':'Liste des emplacements','Карта доступных прокси':'Carte des proxys disponibles','Глобус с доступными прокси':'Globe des proxys disponibles','Свернуть':'Réduire','Развернуть':'Agrandir','Закрыть':'Fermer','Язык':'Langue','Маршрутизация':'Routage','Весь компьютер':'Tout l’ordinateur','Только выбранные программы':'Applications choisies uniquement','Все, кроме выбранных программ':'Toutes sauf les applications choisies','Добавить программу .exe':'Ajouter une application .exe',
      'DNS запросы системы проходят через туннель. После изменения маршрута переподключитесь.':'Les requêtes DNS du système passent par le tunnel. Reconnectez-vous après un changement de routage.','Свой WireGuard':'Votre WireGuard','Профиль не импортирован':'Aucun profil importé','Импорт .conf':'Importer .conf','Удалить':'Supprimer','Приватный ключ хранится в защищённом хранилище Windows. Для подключения нужен свой WireGuard сервер.':'La clé privée est stockée dans le coffre sécurisé de Windows. Vous devez disposer de votre propre serveur WireGuard.',
      'Свой сервер':'Votre serveur','Мой WireGuard':'Mon WireGuard','Неизвестная страна':'Pays inconnu','Качество пинга':'Qualité du ping','из':'sur','Маршрут включён · проверьте IP в программе':'Routage actif · vérifiez l’IP dans l’application','Выходной IP ПК':'IP de sortie du PC','проверить ↗':'vérifier ↗','Ничего не найдено':'Aucun résultat','Ищем доступные локации':'Recherche d’emplacements disponibles','Нет доступных серверов':'Aucun serveur disponible','Подготовка':'Préparation',
      'Серверы появятся здесь по мере проверки.':'Les serveurs apparaîtront ici pendant la vérification.','Попробуйте другой город, страну или тип.':'Essayez une autre ville, un autre pays ou un autre type.','Обновите список позже.':'Actualisez la liste plus tard.','Загружаем публичные списки.':'Chargement des listes de proxys.','Обновление списка':'Actualisation de la liste','Загрузка списка':'Chargement de la liste','Ошибка загрузки':'Échec du chargement','Не удалось загрузить список':'Échec du chargement',
      'Сначала остановите текущее подключение':'Déconnectez d’abord le serveur actuel','Не удалось отключить прокси':'Déconnexion impossible','Прокси отключён':'Déconnecté','Ошибка подключения':'Échec de la connexion','Не удалось включить туннель':'Impossible de démarrer le tunnel','Подключено':'Connecté','Маршрут выбранных программ включён':'Routage des applications choisies actif','Туннель включён; выходной IP проверен':'Tunnel actif ; IP de sortie vérifiée','Маршрут включён. Проверьте IP в выбранной программе':'Routage actif. Vérifiez l’IP dans l’application choisie.',
      'Не удалось изменить настройки Windows':'Impossible de modifier les paramètres Windows','Прокси отключён: сервер перестал отвечать':'Déconnecté : le serveur ne répond plus','Пройдите CAPTCHA в открытом окне Google':'Résolvez le CAPTCHA dans la fenêtre Google','Удалить программу':'Supprimer l’application','Профиль WireGuard импортирован':'Profil WireGuard importé','Поиск серверов':'Recherche de serveurs','Рукопожатие':'Négociation','Проверка IP':'Vérification de l’IP','Запуск WireGuard':'Démarrage de WireGuard','Проверка серверов':'Vérification des serveurs','Сначала остановите соединение':'Déconnectez-vous d’abord','Соединение уже включено':'Déjà connecté','Выберите программу в настройках маршрутизации':'Choisissez une application dans les paramètres de routage','Обновите список и выберите сервер':'Actualisez la liste et choisissez un serveur','Подождите завершения подключения':'Attendez la fin de la tentative de connexion','Сначала импортируйте файл WireGuard .conf':'Importez d’abord un fichier WireGuard .conf'
    },
    es:{
      'Выберите локацию':'Elige una ubicación','Настройки':'Ajustes','Обновить список':'Actualizar lista','Профиль WireGuard не добавлен':'No hay perfil WireGuard','Импортируйте файл .conf в настройках.':'Importa un archivo .conf en Ajustes.','ПОДКЛЮЧЕНИЕ ВЫКЛЮЧЕНО':'SIN CONEXIÓN','СЕРВЕР ВЫБРАН · НЕ ПОДКЛЮЧЕНО':'SERVIDOR ELEGIDO · SIN CONEXIÓN','ТУННЕЛЬ ВКЛЮЧЁН':'TÚNEL ACTIVO',
      'Проверяем серверы в фоне':'Comprobando servidores en segundo plano','Нажмите на страну в списке':'Elige una ubicación de la lista','Город не определён':'Ciudad desconocida','город не определён':'ciudad desconocida','ОТКЛИК':'LATENCIA','Google: где я ↗':'Google: ¿dónde estoy? ↗','Выберите':'Elegir','Пуск':'Conectar','Стоп':'Desconectar','Подождите…':'Espera…',
      'Локации':'Ubicaciones','Страна или город':'País o ciudad','Поиск по стране или городу':'Buscar país o ciudad','Тип прокси':'Tipo de proxy','Все типы':'Todos los tipos','СТРАНА И ГОРОД':'PAÍS Y CIUDAD','ПИНГ':'PING','Карта сети':'Mapa de red','Точки появятся после проверки':'Las ubicaciones aparecerán tras el análisis','Быстрый':'Rápido','Средний':'Medio','Высокий пинг':'Latencia alta','Загружаем список':'Cargando lista',
      'Выбранная локация':'Ubicación elegida','Список локаций':'Lista de ubicaciones','Карта доступных прокси':'Mapa de proxies disponibles','Глобус с доступными прокси':'Globo de proxies disponibles','Свернуть':'Minimizar','Развернуть':'Maximizar','Закрыть':'Cerrar','Язык':'Idioma','Маршрутизация':'Enrutamiento','Весь компьютер':'Todo el equipo','Только выбранные программы':'Solo apps seleccionadas','Все, кроме выбранных программ':'Todas excepto las apps seleccionadas','Добавить программу .exe':'Añadir aplicación .exe',
      'DNS запросы системы проходят через туннель. После изменения маршрута переподключитесь.':'Las consultas DNS del sistema pasan por el túnel. Vuelve a conectarte tras cambiar el enrutamiento.','Свой WireGuard':'Tu WireGuard','Профиль не импортирован':'Ningún perfil importado','Импорт .conf':'Importar .conf','Удалить':'Eliminar','Приватный ключ хранится в защищённом хранилище Windows. Для подключения нужен свой WireGuard сервер.':'La clave privada se guarda en el almacenamiento seguro de Windows. Necesitas tu propio servidor WireGuard.',
      'Свой сервер':'Tu servidor','Мой WireGuard':'Mi WireGuard','Неизвестная страна':'País desconocido','Качество пинга':'Calidad del ping','из':'de','Маршрут включён · проверьте IP в программе':'Enrutamiento activo · comprueba la IP en la app','Выходной IP ПК':'IP de salida del PC','проверить ↗':'comprobar ↗','Ничего не найдено':'Sin resultados','Ищем доступные локации':'Buscando ubicaciones disponibles','Нет доступных серверов':'No hay servidores disponibles','Подготовка':'Preparando',
      'Серверы появятся здесь по мере проверки.':'Los servidores aparecerán aquí al comprobarse.','Попробуйте другой город, страну или тип.':'Prueba otra ciudad, país o tipo.','Обновите список позже.':'Actualiza la lista más tarde.','Загружаем публичные списки.':'Cargando listas de proxies.','Обновление списка':'Actualizando lista','Загрузка списка':'Cargando lista','Ошибка загрузки':'No se pudo cargar la lista','Не удалось загрузить список':'No se pudo cargar la lista',
      'Сначала остановите текущее подключение':'Desconecta primero el servidor actual','Не удалось отключить прокси':'No se pudo desconectar','Прокси отключён':'Desconectado','Ошибка подключения':'Error de conexión','Не удалось включить туннель':'No se pudo iniciar el túnel','Подключено':'Conectado','Маршрут выбранных программ включён':'Enrutamiento de apps seleccionadas activo','Туннель включён; выходной IP проверен':'Túnel activo; IP de salida verificada','Маршрут включён. Проверьте IP в выбранной программе':'Enrutamiento activo. Comprueba la IP en la app seleccionada.',
      'Не удалось изменить настройки Windows':'No se pudo cambiar la configuración de Windows','Прокси отключён: сервер перестал отвечать':'Desconectado: el servidor dejó de responder','Пройдите CAPTCHA в открытом окне Google':'Completa el CAPTCHA en la ventana de Google','Удалить программу':'Eliminar aplicación','Профиль WireGuard импортирован':'Perfil de WireGuard importado','Поиск серверов':'Buscando servidores','Рукопожатие':'Negociación','Проверка IP':'Comprobando IP','Запуск WireGuard':'Iniciando WireGuard','Проверка серверов':'Comprobando servidores','Сначала остановите соединение':'Desconecta primero','Соединение уже включено':'Ya está conectado','Выберите программу в настройках маршрутизации':'Elige una app en los ajustes de enrutamiento','Обновите список и выберите сервер':'Actualiza la lista y elige un servidor','Подождите завершения подключения':'Espera a que termine el intento de conexión','Сначала импортируйте файл WireGuard .conf':'Importa primero un archivo WireGuard .conf'
    }
  };
  Object.assign(translations.tr,{
    'Системный прокси пока доступен только в Windows':'Sistem proxy yalnızca Windows üzerinde kullanılabilir','Туннель доступен только в Windows':'Tünel yalnızca Windows üzerinde kullanılabilir',
    'Сначала подключитесь к серверу':'Önce bir sunucuya bağlanın','В режиме выбранных программ проверяйте IP внутри этих программ':'Seçilen uygulama modunda IP adresini bu uygulamalarda kontrol edin','Координаты выхода неизвестны':'Çıkış koordinatları bilinmiyor'
  });
  Object.assign(translations.de,{
    'Системный прокси пока доступен только в Windows':'System-Proxy ist nur unter Windows verfügbar','Туннель доступен только в Windows':'Der Tunnel ist nur unter Windows verfügbar',
    'Сначала подключитесь к серверу':'Zuerst mit einem Server verbinden','В режиме выбранных программ проверяйте IP внутри этих программ':'Im Modus für ausgewählte Programme die IP in diesen Programmen prüfen','Координаты выхода неизвестны':'Ausgangskoordinaten unbekannt'
  });
  Object.assign(translations.fr,{
    'Системный прокси пока доступен только в Windows':'Le proxy système est disponible uniquement sous Windows','Туннель доступен только в Windows':'Le tunnel est disponible uniquement sous Windows',
    'Сначала подключитесь к серверу':'Connectez-vous d’abord à un serveur','В режиме выбранных программ проверяйте IP внутри этих программ':'En mode applications choisies, vérifiez l’IP dans ces applications','Координаты выхода неизвестны':'Coordonnées de sortie inconnues'
  });
  Object.assign(translations.es,{
    'Системный прокси пока доступен только в Windows':'El proxy del sistema solo está disponible en Windows','Туннель доступен только в Windows':'El túnel solo está disponible en Windows',
    'Сначала подключитесь к серверу':'Conéctate primero a un servidor','В режиме выбранных программ проверяйте IP внутри этих программ':'En el modo de apps seleccionadas, comprueba la IP dentro de esas apps','Координаты выхода неизвестны':'Coordenadas de salida desconocidas'
  });
  const staticItems={
    '#settingsButton':'Настройки','#settingsTitle':'Настройки','#languageLabel':'Язык','#routingLabel':'Маршрутизация',
    '#addProgram':'Добавить программу .exe','#routingNote':'DNS запросы системы проходят через туннель. После изменения маршрута переподключитесь.',
    '#wireguardLabel':'Свой WireGuard','#wireguardNote':'Приватный ключ хранится в защищённом хранилище Windows. Для подключения нужен свой WireGuard сервер.',
    '#importWireGuard':'Импорт .conf','#removeWireGuard':'Удалить',
    '.locations-pane .pane-heading h2':'Локации','.map-pane .pane-heading h2':'Карта сети',
    '.list-head span:first-child':'СТРАНА И ГОРОД','.list-head span:last-child':'ПИНГ',
    '.selected-ping .overline':'ОТКЛИК','#googleLocation':'Google: где я ↗','#mapEmpty':'Точки появятся после проверки',
    '.map-legend span:nth-child(1)':'Быстрый','.map-legend span:nth-child(2)':'Средний','.map-legend span:nth-child(3)':'Высокий пинг'
  };
  const supported=['en','ru','tr','de','fr','es'];
  const saved=localStorage.getItem('veyral-language');
  let language=supported.includes(saved)?saved:'en';
  function t(value){return language==='ru'?value:(translations[language]?.[value]||english[value]||value);}
  const words={
    en:{country:['country','countries'],found:'found',available:'available',reliability:'reliability',checked:'Checked',servers:'servers',select:'Select'},
    tr:{country:['ülke','ülke'],found:'bulundu',available:'kullanılabilir',reliability:'güvenilirlik',checked:'Kontrol edildi:',servers:'sunucu',select:'Seç'},
    de:{country:['Land','Länder'],found:'gefunden',available:'verfügbar',reliability:'Zuverlässigkeit',checked:'Geprüft:',servers:'Server',select:'Wählen'},
    fr:{country:['pays','pays'],found:'trouvés',available:'disponibles',reliability:'fiabilité',checked:'Vérifiés :',servers:'serveurs',select:'Choisir'},
    es:{country:['país','países'],found:'encontrados',available:'disponibles',reliability:'fiabilidad',checked:'Comprobados:',servers:'servidores',select:'Elegir'}
  };
  function countries(n){if(language==='ru'){const ten=n%10,hundred=n%100;return `${n} ${ten===1&&hundred!==11?'страна':ten>=2&&ten<=4&&(hundred<12||hundred>14)?'страны':'стран'}`;}const pair=words[language].country;return `${n} ${pair[n===1?0:1]}`;}
  function availability(n,scanning){return language==='ru'?`${n} ${scanning?'найдено':'доступно'}`:`${n} ${words[language][scanning?'found':'available']}`;}
  function checked(n,total){if(language==='ru')return total===undefined?`Проверено ${n} серверов`:`Проверено ${n} из ${total}`;return total===undefined?`${words[language].checked} ${n} ${words[language].servers}`:`${words[language].checked} ${n} ${t('из')} ${total}`;}
  function latency(ms){return `${Math.round(ms)} ${language==='ru'?'мс':'ms'}`;}
  function reliability(n){return `${n}% ${language==='ru'?'надёжность':words[language].reliability}`;}
  function selectCountry(name){return `${language==='ru'?'Выбрать':words[language].select} ${name}`;}
  function applyStatic(){
    document.documentElement.lang=language;
    for(const [selector,value] of Object.entries(staticItems)){
      const element=document.querySelector(selector);if(!element)continue;
      if(selector.startsWith('.map-legend')){element.lastChild.textContent=` ${t(value)}`;}else element.textContent=t(value);
    }
    for(const select of ['protocol','routingMode'])for(const option of document.querySelector(`#${select}`).options){if(!option.dataset.ru)option.dataset.ru=option.textContent;option.textContent=t(option.dataset.ru);}
    const input=document.querySelector('#search');input.placeholder=t('Страна или город');input.setAttribute('aria-label',t('Поиск по стране или городу'));
    const labels={'#minimize':'Свернуть','#maximize':'Развернуть','#close':'Закрыть','#settingsClose':'Закрыть','#refresh':'Обновить список','#language':'Язык','#protocol':'Тип прокси',
      '.selected':'Выбранная локация','.locations-pane':'Список локаций','.map-pane':'Карта доступных прокси','#globe':'Глобус с доступными прокси'};
    for(const [selector,value] of Object.entries(labels))document.querySelector(selector)?.setAttribute('aria-label',t(value));
    document.querySelector('#refresh').title=t('Обновить список');
  }
  function setLanguage(value){language=supported.includes(value)?value:'en';localStorage.setItem('veyral-language',language);applyStatic();}
  return {t,applyStatic,setLanguage,countries,availability,checked,latency,reliability,selectCountry,get language(){return language;}};
})();
